/**
 * SUPABASE CLIENT CONFIGURATION
 * 
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * 
 * Business Purpose:
 * - Provides database and backend API access for HalalChecker
 * - Enables storage of product verdicts, user reports, and cached data
 * - Powers Edge Functions (serverless backend logic)
 * 
 * Technical Details:
 * - Initializes Supabase client with environment credentials
 * - Configures local storage for session persistence
 * - Auto-refreshes authentication tokens
 * - Uses TypeScript types from Database schema
 * 
 * Usage:
 * import { supabase } from "@/integrations/supabase/client";
 * const { data, error } = await supabase.from('verdicts').select('*');
 */

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Environment variables from .env file (auto-configured by Lovable Cloud)
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Create and export configured Supabase client
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,      // Store auth tokens in browser localStorage
    persistSession: true,        // Keep user logged in across page refreshes
    autoRefreshToken: true,      // Automatically refresh expired tokens
  }
});